# Generated by Django 4.0.4 on 2022-05-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('medium', models.CharField(max_length=500)),
                ('dimensions', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('text', models.CharField(blank=True, max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='backend.pagedata')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=600, null=True)),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_img', to='backend.artwork')),
            ],
        ),
    ]
