# Generated by Django 4.0.4 on 2022-06-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallinks',
            name='splash',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
