export enum ActionTypes {
  /// Auth action types
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  LOGOUT = "LOGOUT",
  /// User action types
  USER_CREATE_REQUEST = "USER_CREATE_REQUEST",
  USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS",
  USER_CREATE_FAIL = "USER_CREATE_FAIL",

  USER_EDIT_REQUEST = "USER_EDIT_REQUEST",
  USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS",
  USER_EDIT_FAIL = "USER_EDIT_FAIL",
  // Page Data action types
  PAGEDATA_REQUEST = "PAGEDATA_REQUEST",
  PAGEDATA_SUCCESS = "PAGEDATA_SUCCESS",
  PAGEDATA_FAIL = "PAGEDATA_FAIL",
  // Artwork list reducers
  ARTWORKLIST_REQUEST = "ARTWORKLIST_REQUEST",
  ARTWORKLIST_SUCCESS = "ARTWORKLIST_SUCCESS",
  ARTWORKLIST_FAIL = "ARTWORKLIST_FAIL",
  // Artwork edit
  ARTWORK_EDIT_REQUEST = "ARTWORK_EDIT_REQUEST",
  ARTWORK_EDIT_SUCCESS = "ARTWORK_EDIT_SUCCESS",
  ARTWORK_EDIT_FAIL = "ARTWORK_EDIT_FAIL",
  /// Other Artwork Actions
  ARTWORK_CREATE_REQUEST = "ARTWORK_CREATE_REQUEST",
  ARTWORK_CREATE_SUCCESS = "ARTWORK_CREATE_SUCCESS",
  ARTWORK_CREATE_FAIL = "ARTWORK_CREATE_FAIL",

  ARTWORK_DELETE_REQUEST = "ARTWORK_DELETE_REQUEST",
  ARTWORK_DELETE_SUCCESS = "ARTWORK_DELETE_SUCCESS",
  ARTWORK_DELETE_FAIL = "ARTWORK_DELETE_FAIL",

  // SINGLE ARTWORK
  ARTWORK_GET_REQUEST = "ARTWORK_GET_REQUEST",
  ARTWORK_GET_SUCCESS = "ARTWORK_GET_SUCCESS",
  ARTWORK_GET_FAIL = "ARTWORK_GET_FAIL",

  // UPLOAD ACTION TYPES
  UPLOAD_REQUEST = "UPLOAD_REQUEST",
  UPLOAD_SUCCESS = "UPLOAD_SUCCESS",
  UPLOAD_FAIL = "UPLOAD_FAIL",

  REMOVE_UPLOAD_REQUEST = "REMOVE_UPLOAD_REQUEST",
  REMOVE_UPLOAD_SUCCESS = "REMOVE_UPLOAD_SUCCESS",
  REMOVE_UPLOAD_FAIL = "REMOVE_UPLOAD_FAIL",

  // MEDIA ACTIONS
  MEDIA_CREATE_REQUEST = "MEDIA_CREATE_REQUEST",
  MEDIA_CREATE_SUCCESS = "MEDIA_CREATE_SUCCESS",
  MEDIA_CREATE_FAIL = "MEDIA_CREATE_FAIL",
  MEDIA_DELETE_REQUEST = "MEDIA_DELETE_REQUEST",
  MEDIA_DELETE_SUCCESS = "MEDIA_DELETE_SUCCESS",
  MEDIA_DELETE_FAIL = "MEDIA_DELETE_FAIL",
}
