export enum ActionTypes {
  /// Auth action types
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  LOGOUT = "LOGOUT",
<<<<<<< HEAD
  // Page Data action types
  PAGEDATA_REQUEST = "PAGEDATA_REQUEST",
  PAGEDATA_SUCCESS = "PAGEDATA_SUCCESS",
  PAGEDATA_FAIL = "PAGEDATA_FAIL",
  // Artwork list reducers
  ARTWORKLIST_REQUEST = "ARTWORKLIST_REQUEST",
  ARTWORKLIST_SUCCESS = "ARTWORKLIST_SUCCESS",
  ARTWORKLIST_FAIL = "ARTWORKLIST_FAIL",
  // Artwork edit
  ARTWORK_EDIT_REQUEST = "ARTWORK_EDIT_REQUEST",
  ARTWORK_EDIT_SUCCESS = "ARTWORK_EDIT_SUCCESS",
  ARTWORK_EDIT_FAIL = "ARTWORK_EDIT_FAIL",
=======
>>>>>>> parent of 9a4e4fa... setting up redux for siteData
}
