export enum ActionTypes {
  /// Auth action types
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  LOGOUT = "LOGOUT",

  /// Artwork action types
  ARTWORKLIST_GET_REQUEST = "ARTWORKLIST_GET_REQUEST",
  ARTWORKLIST_GET_SUCCESS = "ARTWORKLIST_GET_SUCCESS",
  ARTWORKLIST_GET_FAIL = "ARTWORKLIST_GET_FAIL",

  ARTWORK_GET_REQUEST = "ARTWORK_GET_REQUEST",
  ARTWORK_GET_SUCCESS = "ARTWORK_GET_SUCCESS",
  ARTWORK_GET_FAIL = "ARTWORK_GET_FAIL",

  ARTWORK_CREATE_REQUEST = "ARTWORK_CREATE_REQUEST",
  ARTWORK_CREATE_SUCCESS = "ARTWORK_CREATE_SUCCESS",
  ARTWORK_CREATE_FAIL = "ARTWORK_CREATE_FAIL",

  ARTWORK_EDIT_REQUEST = "ARTWORK_EDIT_REQUEST",
  ARTWORK_EDIT_SUCCESS = "ARTWORK_EDIT_SUCCESS",
  ARTWORK_EDIT_FAIL = "ARTWORK_EDIT_FAIL",

  ARTWORK_DELETE_REQUEST = "ARTWORK_DELETE_REQUEST",
  ARTWORK_DELETE_SUCCESS = "ARTWORK_DELETE_SUCCESS",
  ARTWORK_DELETE_FAIL = "ARTWORK_DELETE_FAIL",

  /// User action types
  USER_CREATE_REQUEST = "USER_CREATE_REQUEST",
  USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS",
  USER_CREATE_FAIL = "USER_CREATE_FAIL",

  USER_EDIT_REQUEST = "USER_EDIT_REQUEST",
  USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS",
  USER_EDIT_FAIL = "USER_EDIT_FAIL",

  /// PageData action types
  PAGEDATA_CREATE_REQUEST = "PAGEDATA_CREATE_REQUEST",
  PAGEDATA_CREATE_SUCCESS = "PAGEDATA_CREATE_SUCCESS",
  PAGEDATA_CREATE_FAIL = "PAGEDATA_CREATE_FAIL",

  PAGEDATA_EDIT_REQUEST = "PAGEDATA_EDIT_REQUEST",
  PAGEDATA_EDIT_SUCCESS = "PAGEDATA_EDIT_SUCCESS",
  PAGEDATA_EDIT_FAIL = "PAGEDATA_EDIT_FAIL",

  // UPLOAD ACTION TYPES
  UPLOAD_EDIT_REQUEST = "UPLOAD_EDIT_REQUEST",
  UPLOAD_EDIT_SUCCESS = "UPLOAD_EDIT_SUCCESS",
  UPLOAD_EDIT_FAIL = "UPLOAD_EDIT_FAIL",
}
